services:
  - type: web
    name: justice-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn justice-project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project_phoenix.settings
      - key: SECRET_KEY
        value: 1@3@v1(g(z!svb6j=_0=^yfl7-x8ygr39$c9%g1m+*+@80@bta
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: justice-project.onrender.com
