# Generated by Django 4.2.19 on 2025-04-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_behaviorallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='adblocker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='color_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='incognito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='touch_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='referrer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
